#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define RANDOM_STRENGTH    2
#define CH32V003           1

#define FUNCONF_USE_DEBUGPRINTF 0
#define FUNCONF_USE_UARTPRINTF  1
#define FUNCONF_UART_PRINTF_BAUD 115200

#endif

